// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

export const AdminSignUpApiSlice = createApi({
    baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:8000" }),
    reducerPath: "adminSignUpApi",
    tagTypes: ["User"],
    endpoints: (build) => ({
        // POST 요청을 위한 엔드포인트 정의
        createUser: build.mutation({
            query: (userData) => ({
                url: "/user/create", // POST 요청을 보낼 경로
                method: "POST", // HTTP 메서드 지정
                body: userData, // 전달할 데이터
                headers: {
                    "Content-Type": "application/json",
                },
            }),
            invalidatesTags: [{ type: "User", id: "LIST" }],
        }),
        loginUser: build.mutation({
            query: (userData) => ({
                url: "/user/signIn", // POST 요청을 보낼 경로
                method: "POST", // HTTP 메서드 지정
                body: userData, // 전달할 데이터
                headers: {
                    "Content-Type": "application/json",
                },
            }),
            invalidatesTags: [{ type: "User", id: "LIST" }],
        }),
        authUser: build.mutation({
            query: (tokenData) => ({
                url: "/user/auth", // POST 요청을 보낼 경로
                method: "POST", // HTTP 메서드 지정
                body: tokenData, // 전달할 데이터
                headers: {
                    "Content-Type": "application/json",
                },
            }),
            invalidatesTags: [{ type: "User", id: "LIST" }],
        })
    }),
})


// Hooks are auto-generated by RTK Query
// `useCreateUserMutation` Hook을 사용하여 POST 요청 수행
export const { useCreateUserMutation, useLoginUserMutation, useAuthUserMutation } = AdminSignUpApiSlice